### ISSUE TITLE
linux script

### ISSUE THREAD

**Issue by bigmac5753** [Flora-Network/fd-cli#20]
Is an automated linux script available?

**Comment by stanchiam** [comment]
i created one, just create a file(eg recoverCoin) and chmod +x recoverCoin and run it by typing ./recoverCoin
Copy and paste content below and add in your LAUNCHER_HASH and POOL_CONTRACT_ADDRESS


#!/usr/bin/env bash

set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.apple/mainnet/db/blockchain_v1_mainnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.apple/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 26665 -ct $HOME/.apple/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.apple/mainnet/config/ssl/full_node/private_full_node.key
deactivate

set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.avocado/mainnet/db/blockchain_v1_mainnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.avocado/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 7544 -ct $HOME/.avocado/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.avocado/mainnet/config/ssl/full_node/private_full_node.key
deactivate

set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.btcgreen/mainnet/db/blockchain_v1_mainnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.btcgreen/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 18942 -ct $HOME/.btcgreen/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.btcgreen/mainnet/config/ssl/full_node/private_full_node.key
deactivate

#
set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.cactus/mainnet/db/blockchain_v1_mainnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.cactus/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 11555 -ct $HOME/.cactus/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.cactus/mainnet/config/ssl/full_node/private_full_node.key
deactivate

set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.cannabis/mainnet/db/blockchain_v1_mainnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.cannabis/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 5540 -ct $HOME/.cannabis/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.cannabis/mainnet/config/ssl/full_node/private_full_node.key
deactivate

set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.chaingreen/mainnet/db/blockchain_v1_mainnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.chaingreen/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 8855 -ct $HOME/.chaingreen/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.chaingreen/mainnet/config/ssl/full_node/private_full_node.key
deactivate

set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.chiarose/mainnet/db/blockchain_v1_mainnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.chiarose/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 8025 -ct $HOME/.chiarose/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.chiarose/mainnet/config/ssl/full_node/private_full_node.key
deactivate

set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.covid/mainnet/db/blockchain_v1_mainnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.covid/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 18135 -ct $HOME/.covid/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.covid/mainnet/config/ssl/full_node/private_full_node.key
deactivate

set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.dogechia/mainnet/db/blockchain_v1_mainnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.dogechia/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 6769 -ct $HOME/.dogechia/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.dogechia/mainnet/config/ssl/full_node/private_full_node.key
deactivate

set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.equality/mainnet/db/blockchain_v1_mainnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.equality/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 9755 -ct $HOME/.equality/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.equality/mainnet/config/ssl/full_node/private_full_node.key
deactivate

set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.chia/ext9/db/blockchain_v1_ext9.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.chia/ext9/wallet/db/blockchain_wallet_v1_ext9_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 38555 -ct $HOME/.chia/ext9/config/ssl/full_node/private_full_node.crt -ck $HOME/.chia/ext9/config/ssl/full_node/private_full_node.key
deactivate

set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.flax/mainnet/db/blockchain_v1_mainnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.flax/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 6755 -ct $HOME/.flax/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.flax/mainnet/config/ssl/full_node/private_full_node.key
deactivate

set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.flora/mainnet/db/blockchain_v1_mainnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.flora/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 18755 -ct $HOME/.flora/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.flora/mainnet/config/ssl/full_node/private_full_node.key
deactivate

set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.goji-blockchain/mainnet/db/blockchain_v1_mainnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.goji-blockchain/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 7555 -ct $HOME/.goji-blockchain/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.goji-blockchain/mainnet/config/ssl/full_node/private_full_node.key
deactivate

set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.greendoge/mainnet/db/blockchain_v1_mainnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.greendoge/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 6655 -ct $HOME/.greendoge/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.greendoge/mainnet/config/ssl/full_node/private_full_node.key
deactivate

#
set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.hddcoin/mainnet/db/blockchain_v1_mainnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.hddcoin/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 28555 -ct $HOME/.hddcoin/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.hddcoin/mainnet/config/ssl/full_node/private_full_node.key
deactivate

set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.kale/mainnet/db/blockchain_v1_mainnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.kale/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 6355 -ct $HOME/.kale/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.kale/mainnet/config/ssl/full_node/private_full_node.key
deactivate

set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.littlelambocoin/mainnet/db/blockchain_v1_mainnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.littlelambocoin/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 28625 -ct $HOME/.littlelambocoin/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.littlelambocoin/mainnet/config/ssl/full_node/private_full_node.key
deactivate

set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.lucky/mainnet/db/blockchain_v1_mainnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.lucky/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 16655 -ct $HOME/.lucky/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.lucky/mainnet/config/ssl/full_node/private_full_node.key
deactivate

set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.maize/mainnet/db/blockchain_v1_mainnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.maize/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 8655 -ct $HOME/.maize/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.maize/mainnet/config/ssl/full_node/private_full_node.key
deactivate

set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.melati/mainnet/db/blockchain_v1_mainnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.melati/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 2555 -ct $HOME/.melati/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.melati/mainnet/config/ssl/full_node/private_full_node.key
deactivate

set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.scam/mainnet/db/blockchain_v1_mainnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.scam/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 9655 -ct $HOME/.scam/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.scam/mainnet/config/ssl/full_node/private_full_node.key
deactivate

set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.sector/mainnet/db/blockchain_v1_mainnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.sector/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 5555 -ct $HOME/.sector/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.sector/mainnet/config/ssl/full_node/private_full_node.key
deactivate

set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.seno2/mainnet/db/blockchain_v1_mainnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.seno2/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 18555 -ct $HOME/.seno2/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.seno2/mainnet/config/ssl/full_node/private_full_node.key
deactivate

set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.silicoin/mainnet/db/blockchain_v1_testnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.silicoin/mainnet/wallet/db/blockchain_wallet_v1_testnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 10555 -ct $HOME/.silicoin/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.silicoin/mainnet/config/ssl/full_node/private_full_node.key
deactivate

set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.socks/mainnet/db/blockchain_v1_mainnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.socks/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 58455 -ct $HOME/.socks/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.socks/mainnet/config/ssl/full_node/private_full_node.key
deactivate

set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.spare-blockchain/mainnet/db/blockchain_v1_mainnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.spare-blockchain/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 9555 -ct $HOME/.spare-blockchain/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.spare-blockchain/mainnet/config/ssl/full_node/private_full_node.key
deactivate

set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.taco/mainnet/db/blockchain_v1_mainnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.taco/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 18735 -ct $HOME/.taco/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.taco/mainnet/config/ssl/full_node/private_full_node.key
deactivate

set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.tad/mainnet/db/blockchain_v1_mainnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.tad/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 4555 -ct $HOME/.tad/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.tad/mainnet/config/ssl/full_node/private_full_node.key
deactivate

# set -e
# source /home/scm/fd-cli/venv/bin/activate
# export FD_CLI_BC_DB_PATH=$HOME/.thyme/mainnet/db/blockchain_v1_mainnet.sqlite
# export FD_CLI_WT_DB_PATH=$HOME/.thyme/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
# export LAUNCHER_HASH=
# export POOL_CONTRACT_ADDRESS=
# fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 16755 -ct $HOME/.thyme/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.thyme/mainnet/config/ssl/full_node/private_full_node.key
# deactivate

set -e
source /home/scm/fd-cli/venv/bin/activate
export FD_CLI_BC_DB_PATH=$HOME/.wheat/mainnet/db/blockchain_v1_mainnet.sqlite
export FD_CLI_WT_DB_PATH=$HOME/.wheat/mainnet/wallet/db/blockchain_wallet_v1_mainnet_105931933.sqlite
export LAUNCHER_HASH=
export POOL_CONTRACT_ADDRESS=
fd-cli nft-recover -l "$LAUNCHER_HASH" -p "$POOL_CONTRACT_ADDRESS" -nh 127.0.0.1 -np 21555 -ct $HOME/.wheat/mainnet/config/ssl/full_node/private_full_node.crt -ck $HOME/.wheat/mainnet/config/ssl/full_node/private_full_node.key
deactivate

**Comment by stanchiam** [comment]
Btw, cactus-blockchain does not work, the coins are found but not send back to the wallet, the rest of the forks are ok. Cactus need to use their forked fd-cli then ok.

**Comment by jfikar** [comment]
I see, good to know. There is also GreenDoge [fork of fd-cli](https://github.com/GreenDoge-Network/fd-cli). Not sure if it is any different.

**Comment by stanchiam** [comment]
greendoge is working for me, only cactus is not, waited long time the wallet is not updated for cactus but if i run the fd-cli from cactus fork, wallet will be updated in a few mins

**Comment by laz954** [comment]
Do you have to be doing Self Pooling in order to use the script ?

**Comment by Abrahimsafi2021** [comment]
Guys, I have problem when I enter the script, my script:

#Skynet
**source /home/fd-cli/venv/bin/activate**
export FD_CLI_BC_DB_PATH=$HOME/.skynet/mainnet/db/blockchain_v1_testnet_09.sqlite
export FD_CLI_WT_DB_PATH=/home/siyer/.skynet/mainnet/wallet/db/blockchain_wallet_v1_testnet_09_3********7.sqlite
export LAUNCHER_HASH=657ce791adca8b***************************************************
export POOL_CONTRACT_ADDRESS=xch12t*************************************************

  fd-cli nft-recover \
  -l "657ce7***************************************************8fa" \
  -p "xch12t***************************************************ea" \
  -nh 127.0.0.1 \
  -np 9999 \
  -ct "/home/siyer/.skynet/mainnet/config/ssl/full_node/private_full_node.crt" \
  -ck "/home/siyer/.skynet/mainnet/config/ssl/full_node/private_full_node.key"


Here is my error:
It can find coins but cant recover:     

Coins eligible for recovery:

  An error occurred while sending the recovery transaction.
Traceback (most recent call last):
  File "/home/siyer/fd-cli/venv/bin/fd-cli", line 33, in <module>
    sys.exit(load_entry_point('fd-cli', 'console_scripts', 'fd-cli')())
  File "/home/siyer/fd-cli/fd_cli/fd_cli.py", line 220, in main
    fd_cli()
  File "/home/siyer/fd-cli/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/siyer/fd-cli/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/siyer/fd-cli/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/siyer/fd-cli/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/siyer/fd-cli/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/siyer/fd-cli/venv/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/siyer/fd-cli/fd_cli/fd_cli.py", line 193, in fd_cli_nft_recover
    fd_cli_cmd_nft_recover(
  File "/home/siyer/fd-cli/fd_cli/fd_cli_cmd_nft_recover.py", line 211, in fd_cli_cmd_nft_recover
    fd_cli_print_raw(exception, pre=pre)
  File "/home/siyer/fd-cli/fd_cli/fd_cli_print.py", line 15, in fd_cli_print_raw
    print(f'{" " * pre * 4}{value:{fill}s}')
TypeError: unsupported format string passed to ConnectionError.__format__

**Comment by jfikar** [comment]
Probably your port number 9999 is wrong, that's the full_node port for Skynet. You need the `rpc_port:` number, which is in `.skynet/mainnet/config/config.xml`

**Comment by Abrahimsafi2021** [comment]
> Probably your port number 9999 is wrong, that's the full_node port for Skynet. You need the `rpc_port:` number, which is in `.skynet/mainnet/config/config.xml`

Thanks for replying, I don't think if there is problem with port number, anyway I've tried with `rpc_port:`, the result is same, it can found the coins but can NOT recover it

**Comment by jfikar** [comment]
It seems Skynet has its own [tool](https://github.com/SkynetNetwork/nft-rewards-recovery) and the port number should be `-np 18755`.

**Comment by Abrahimsafi2021** [comment]
> It seems Skynet has its own [tool](https://github.com/SkynetNetwork/nft-rewards-recovery) and the port number should be `-np 18755`.

I tried with this port too, it's does not work, I also tried their tool it's same error, it's not just for Skynet other coins have same issue, can find coins but can not recover them.

This is the error when found the coins:
Coins eligible for recovery:
            hash:                     546b20ced3c26f47a12e0ddb0******f15128bc32ef1c360f610b35e421
            puzzle_hash:              52dc3d6c2d7372d85534a******dc5a990fb0a3a9f85e4
            amount:                   4375000000000
            timestamp:                1633952210
            --------                 
            hash:                     676627b0f732e599d*****f87903f4725c475256de4eb0f1fc851
            puzzle_hash:              52dc3d6c2d737*****f28327d82336fd4632dc5a990fb0a3a9f85e4
            amount:                   4375000000000
            timestamp:                1633948499
            --------                 
            hash:                     7c1fc5b31e7788354ca039*****f11dfb087f8e9d088b95de927e45
            puzzle_hash:              52dc3d6c2d73*****f27d82336fd4632dc5a990fb0a3a9f85e4
            amount:                   4375000000000
            timestamp:                1633943727
    An error occurred while sending the recovery transaction.
Traceback (most recent call last):
  File "/home/siyer/fd-cli/skynet/nft-rewards-recovery/venv/bin/fd-cli", line 33, in <module>
    sys.exit(load_entry_point('nft-rewards-recovery', 'console_scripts', 'fd-cli')())
  File "/home/siyer/fd-cli/skynet/nft-rewards-recovery/fd_cli/fd_cli.py", line 220, in main
    fd_cli()
  File "/home/siyer/fd-cli/skynet/nft-rewards-recovery/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/siyer/fd-cli/skynet/nft-rewards-recovery/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/siyer/fd-cli/skynet/nft-rewards-recovery/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/siyer/fd-cli/skynet/nft-rewards-recovery/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/siyer/fd-cli/skynet/nft-rewards-recovery/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/siyer/fd-cli/skynet/nft-rewards-recovery/venv/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/siyer/fd-cli/skynet/nft-rewards-recovery/fd_cli/fd_cli.py", line 193, in fd_cli_nft_recover
    fd_cli_cmd_nft_recover(
  File "/home/siyer/fd-cli/skynet/nft-rewards-recovery/fd_cli/fd_cli_cmd_nft_recover.py", line 211, in fd_cli_cmd_nft_recover
    fd_cli_print_raw(exception, pre=pre)
  File "/home/siyer/fd-cli/skynet/nft-rewards-recovery/fd_cli/fd_cli_print.py", line 15, in fd_cli_print_raw
    print(f'{" " * pre * 4}{value:{fill}s}')
TypeError: unsupported format string passed to ConnectionError.__format__
    No coins are eligible for recovery yet. Notice that 604800 seconds must pass since coin creation to recover it.
