### ISSUE TITLE
OperationalError: no such column: spent | with the upcoming v2 blockchain db format

### ISSUE THREAD

**Issue by ami911** [Flora-Network/fd-cli#23]
I use the fd-cli script on Ubuntu to do the 7/8 nft recovery on all my forks. This works fine so far for all forks except for bpx. 

With bpx I get an error message saying: "sqlite3.OperationalError: no such column: spent" 

It might have something to do with the new chia v2 database they use, all other forks use v1.

Since chia will also officially switch to v2, it might make sense to adapt the fd-cli script accordingly.

Thank you!

--------------------------

Full error trace:

Traceback (most recent call last):
  File "/home/am/fd-cli/venv/bin/fd-cli", line 33, in <module>
    sys.exit(load_entry_point('fd-cli', 'console_scripts', 'fd-cli')())
  File "/home/am/fd-cli/fd_cli/fd_cli.py", line 220, in main
    fd_cli()
  File "/home/am/fd-cli/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/am/fd-cli/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/am/fd-cli/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/am/fd-cli/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/am/fd-cli/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/am/fd-cli/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/am/fd-cli/fd_cli/fd_cli.py", line 193, in fd_cli_nft_recover
    fd_cli_cmd_nft_recover(
  File "/home/am/fd-cli/fd_cli/fd_cli_cmd_nft_recover.py", line 106, in fd_cli_cmd_nft_recover
    db_bc_cursor.execute(
sqlite3.OperationalError: no such column: spent

**Comment by SirCotare** [comment]
There actually are some other issue that need to be fixed, but nothing really dramatic. They didn't change anything about how things generally work.
I'll see if I can patch something together and make a PR. Maybe in a few days...

**Comment by jfikar** [comment]
What is the progress on the v2 DB support?
